#!/bin/bash
set -e

REGION="${AWS_REGION}"
ECR_REPO="${ECR_REPOSITORY}"
S3_BUCKET="${S3_BUCKET}"
CONTAINER_NAME="dockpaas-app"
BLUE_PORT=8081
GREEN_PORT=8082
CURRENT_PORT=8081

echo "=== DockPaaS Deployment Started at $(date) ==="

aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO

echo "Pulling latest image..."
docker pull $ECR_REPO:latest

CURRENT_CONTAINER=$(docker ps --filter "name=$CONTAINER_NAME" --format "{{.ID}}" | head -1)
if [ ! -z "$CURRENT_CONTAINER" ]; then
    CURRENT_PORT=$(docker port $CURRENT_CONTAINER | grep 8081 | cut -d: -f2 || echo "8081")
    echo "Current container running on port: $CURRENT_PORT"
fi

if [ "$CURRENT_PORT" == "$BLUE_PORT" ]; then
    NEW_PORT=$GREEN_PORT
else
    NEW_PORT=$BLUE_PORT
fi

echo "Starting new container on port: $NEW_PORT"

NEW_CONTAINER=$(docker run -d \
    --name ${CONTAINER_NAME}-new \
    -p $NEW_PORT:8081 \
    --restart unless-stopped \
    $ECR_REPO:latest)

echo "Waiting for health check..."
sleep 10
for i in {1..12}; do
    if curl -f http://localhost:$NEW_PORT/health > /dev/null 2>&1; then
        echo "Health check passed!"
        break
    fi
    echo "Attempt $i: Waiting for app to be ready..."
    sleep 5
done

if [ ! -z "$CURRENT_CONTAINER" ]; then
    echo "Stopping old container..."
    docker stop $CURRENT_CONTAINER || true
    docker rm $CURRENT_CONTAINER || true
fi

docker rename ${CONTAINER_NAME}-new $CONTAINER_NAME

iptables -t nat -F PREROUTING
iptables -t nat -A PREROUTING -p tcp --dport 8081 -j REDIRECT --to-port $NEW_PORT

TIMESTAMP=$(date +%Y%m%d-%H%M%S)
REPORT_FILE="/tmp/deployment-$TIMESTAMP.md"

cat > $REPORT_FILE << EOF
# Deployment Report - $TIMESTAMP

## Deployment Details
- **Time**: $(date)
- **Instance ID**: $(ec2-metadata --instance-id | cut -d " " -f 2)
- **Region**: $REGION
- **Image**: $ECR_REPO:latest

## Container Info
- **Container ID**: $NEW_CONTAINER
- **Port**: $NEW_PORT
- **Status**: Running

## Health Check
\`\`\`
$(curl -s http://localhost:$NEW_PORT/health)
\`\`\`

## System Metrics
- **CPU Usage**: $(top -bn1 | grep "Cpu(s)" | awk '{print $2}')%
- **Memory**: $(free -h | awk '/^Mem:/ {print $3 "/" $2}')
- **Disk**: $(df -h / | awk 'NR==2 {print $3 "/" $2}')

## Container Logs (Last 20 lines)
\`\`\`
$(docker logs --tail 20 $NEW_CONTAINER 2>&1)
\`\`\`

---
*Generated by DockPaaS*
EOF

echo "Uploading deployment report to S3..."
aws s3 cp $REPORT_FILE s3://$S3_BUCKET/deployments/deployment-$TIMESTAMP.md --acl public-read

cat > /tmp/index.html << INDEXEOF
<!DOCTYPE html>
<html>
<head>
    <title>DockPaaS Deployments</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }
        h1 { color: #232f3e; }
        .deployment { background: white; padding: 20px; margin: 10px 0; border-radius: 5px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        a { color: #ff9900; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <h1>🚀 DockPaaS Deployment History</h1>
    <div class="deployment">
        <h3>Latest Deployment: $TIMESTAMP</h3>
        <p><a href="deployments/deployment-$TIMESTAMP.md">View Report</a></p>
    </div>
</body>
</html>
INDEXEOF

aws s3 cp /tmp/index.html s3://$S3_BUCKET/index.html --acl public-read --content-type "text/html"

echo "=== Deployment Completed Successfully ==="
